server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teaching_resource_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:files/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl